ingress: 
  ingressClassName: <TF_POPULATED>
  host: <TF_POPULATED>
  portNumber: 3000
  annotations: 
    kubernetes.io/ingress.class: <TF_POPULATED>
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    external-dns.alpha.kubernetes.io/alias: "true"

    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: nextjs-grpc
    alb.ingress.kubernetes.io/load-balancer-name: nextjs-grpc
    alb.ingress.kubernetes.io/security-groups: <TF_POPULATED>
    external-dns.alpha.kubernetes.io/hostname: <TF_POPULATED>

service:
  type: <TF_POPULATED>

podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-pre-populate-only: "true"
  vault.hashicorp.com/tls-secret: "vault-api-tls-client-ca" 
  vault.hashicorp.com/agent-configmap: "vault-secrets-grafana" 
  vault.hashicorp.com/secret-volume-path: /vault

dashboardName: grafana
